//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:34:06 AM MSK 
//


package app.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DriverLicense complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DriverLicense"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}BaseCard"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="drivingExperience" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="firstLicensedDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DriverLicense", propOrder = {
    "drivingExperience",
    "firstLicensedDate"
})
public class DriverLicense
    extends BaseCard
{

    protected Long drivingExperience;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstLicensedDate;

    /**
     * Gets the value of the drivingExperience property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDrivingExperience() {
        return drivingExperience;
    }

    /**
     * Sets the value of the drivingExperience property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDrivingExperience(Long value) {
        this.drivingExperience = value;
    }

    /**
     * Gets the value of the firstLicensedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstLicensedDate() {
        return firstLicensedDate;
    }

    /**
     * Sets the value of the firstLicensedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstLicensedDate(XMLGregorianCalendar value) {
        this.firstLicensedDate = value;
    }

}
