//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:34:06 AM MSK 
//


package app.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for InsuranceContract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuranceContract"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="insuranceContract" type="{}InsuranceContractInner"/&gt;
 *         &lt;element name="internalIds" type="{}InternalIds"/&gt;
 *         &lt;element name="parties" type="{}Parties" maxOccurs="unbounded"/&gt;
 *         &lt;element name="requestType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vehicle" type="{}Vehicle"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceContract", propOrder = {
    "insuranceContract",
    "internalIds",
    "parties",
    "requestType",
    "vehicle"
})
public class InsuranceContract {

    @XmlElement(required = true)
    protected InsuranceContractInner insuranceContract;
    @XmlElement(required = true)
    protected InternalIds internalIds;
    @XmlElement(required = true)
    protected List<Parties> parties;
    protected String requestType;
    @XmlElement(required = true)
    protected Vehicle vehicle;

    /**
     * Gets the value of the insuranceContract property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceContractInner }
     *     
     */
    public InsuranceContractInner getInsuranceContract() {
        return insuranceContract;
    }

    /**
     * Sets the value of the insuranceContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceContractInner }
     *     
     */
    public void setInsuranceContract(InsuranceContractInner value) {
        this.insuranceContract = value;
    }

    /**
     * Gets the value of the internalIds property.
     * 
     * @return
     *     possible object is
     *     {@link InternalIds }
     *     
     */
    public InternalIds getInternalIds() {
        return internalIds;
    }

    /**
     * Sets the value of the internalIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalIds }
     *     
     */
    public void setInternalIds(InternalIds value) {
        this.internalIds = value;
    }

    /**
     * Gets the value of the parties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parties }
     * 
     * 
     */
    public List<Parties> getParties() {
        if (parties == null) {
            parties = new ArrayList<Parties>();
        }
        return this.parties;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestType(String value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * @return
     *     possible object is
     *     {@link Vehicle }
     *     
     */
    public Vehicle getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vehicle }
     *     
     */
    public void setVehicle(Vehicle value) {
        this.vehicle = value;
    }

}
