//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:34:06 AM MSK 
//


package app.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.vsk.eosago.loader.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EGarantPolicy_QNAME = new QName("", "eGarantPolicy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.vsk.eosago.loader.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EGarantPolicy }
     * 
     */
    public EGarantPolicy createEGarantPolicy() {
        return new EGarantPolicy();
    }

    /**
     * Create an instance of {@link SysInfo }
     * 
     */
    public SysInfo createSysInfo() {
        return new SysInfo();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link ResponseData }
     * 
     */
    public ResponseData createResponseData() {
        return new ResponseData();
    }

    /**
     * Create an instance of {@link ProcessingResult }
     * 
     */
    public ProcessingResult createProcessingResult() {
        return new ProcessingResult();
    }

    /**
     * Create an instance of {@link EgarantContractData }
     * 
     */
    public EgarantContractData createEgarantContractData() {
        return new EgarantContractData();
    }

    /**
     * Create an instance of {@link DocumentsCheckData }
     * 
     */
    public DocumentsCheckData createDocumentsCheckData() {
        return new DocumentsCheckData();
    }

    /**
     * Create an instance of {@link CheckInfo }
     * 
     */
    public CheckInfo createCheckInfo() {
        return new CheckInfo();
    }

    /**
     * Create an instance of {@link InsuranceContract }
     * 
     */
    public InsuranceContract createInsuranceContract() {
        return new InsuranceContract();
    }

    /**
     * Create an instance of {@link InsuranceContractInner }
     * 
     */
    public InsuranceContractInner createInsuranceContractInner() {
        return new InsuranceContractInner();
    }

    /**
     * Create an instance of {@link InternalIds }
     * 
     */
    public InternalIds createInternalIds() {
        return new InternalIds();
    }

    /**
     * Create an instance of {@link Parties }
     * 
     */
    public Parties createParties() {
        return new Parties();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link Rates }
     * 
     */
    public Rates createRates() {
        return new Rates();
    }

    /**
     * Create an instance of {@link Stoas }
     * 
     */
    public Stoas createStoas() {
        return new Stoas();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link BaseDoc }
     * 
     */
    public BaseDoc createBaseDoc() {
        return new BaseDoc();
    }

    /**
     * Create an instance of {@link BaseCard }
     * 
     */
    public BaseCard createBaseCard() {
        return new BaseCard();
    }

    /**
     * Create an instance of {@link VehicleDocument }
     * 
     */
    public VehicleDocument createVehicleDocument() {
        return new VehicleDocument();
    }

    /**
     * Create an instance of {@link DriverLicense }
     * 
     */
    public DriverLicense createDriverLicense() {
        return new DriverLicense();
    }

    /**
     * Create an instance of {@link IdentityCard }
     * 
     */
    public IdentityCard createIdentityCard() {
        return new IdentityCard();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EGarantPolicy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eGarantPolicy")
    public JAXBElement<EGarantPolicy> createEGarantPolicy(EGarantPolicy value) {
        return new JAXBElement<EGarantPolicy>(_EGarantPolicy_QNAME, EGarantPolicy.class, null, value);
    }

}
