//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:34:06 AM MSK 
//


package app.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Person"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="badHistoryBasis" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="identityCard" type="{}IdentityCard"/&gt;
 *         &lt;element name="driverLicense" type="{}DriverLicense"/&gt;
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mdmId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="inn" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="kbmRequestId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kbmValue" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="snils" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person", propOrder = {
    "badHistoryBasis",
    "identityCard",
    "driverLicense",
    "phone",
    "email",
    "mdmId",
    "inn",
    "kbmRequestId",
    "kbmValue",
    "snils"
})
public class Person {

    protected Long badHistoryBasis;
    @XmlElement(required = true)
    protected IdentityCard identityCard;
    @XmlElement(required = true)
    protected DriverLicense driverLicense;
    @XmlElement(required = true)
    protected String phone;
    @XmlElement(required = true)
    protected String email;
    protected Long mdmId;
    protected Long inn;
    protected String kbmRequestId;
    protected Long kbmValue;
    protected String snils;

    /**
     * Gets the value of the badHistoryBasis property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBadHistoryBasis() {
        return badHistoryBasis;
    }

    /**
     * Sets the value of the badHistoryBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBadHistoryBasis(Long value) {
        this.badHistoryBasis = value;
    }

    /**
     * Gets the value of the identityCard property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityCard }
     *     
     */
    public IdentityCard getIdentityCard() {
        return identityCard;
    }

    /**
     * Sets the value of the identityCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityCard }
     *     
     */
    public void setIdentityCard(IdentityCard value) {
        this.identityCard = value;
    }

    /**
     * Gets the value of the driverLicense property.
     * 
     * @return
     *     possible object is
     *     {@link DriverLicense }
     *     
     */
    public DriverLicense getDriverLicense() {
        return driverLicense;
    }

    /**
     * Sets the value of the driverLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link DriverLicense }
     *     
     */
    public void setDriverLicense(DriverLicense value) {
        this.driverLicense = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the mdmId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMdmId() {
        return mdmId;
    }

    /**
     * Sets the value of the mdmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMdmId(Long value) {
        this.mdmId = value;
    }

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInn() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInn(Long value) {
        this.inn = value;
    }

    /**
     * Gets the value of the kbmRequestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKbmRequestId() {
        return kbmRequestId;
    }

    /**
     * Sets the value of the kbmRequestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKbmRequestId(String value) {
        this.kbmRequestId = value;
    }

    /**
     * Gets the value of the kbmValue property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getKbmValue() {
        return kbmValue;
    }

    /**
     * Sets the value of the kbmValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setKbmValue(Long value) {
        this.kbmValue = value;
    }

    /**
     * Gets the value of the snils property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnils() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnils(String value) {
        this.snils = value;
    }

}
