//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:34:06 AM MSK 
//


package app.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessingResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessingResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="egarantContractData" type="{}EgarantContractData"/&gt;
 *         &lt;element name="documentsCheckData" type="{}DocumentsCheckData" minOccurs="0"/&gt;
 *         &lt;element name="insuranceContract" type="{}InsuranceContract"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessingResult", propOrder = {
    "egarantContractData",
    "documentsCheckData",
    "insuranceContract"
})
public class ProcessingResult {

    @XmlElement(required = true)
    protected EgarantContractData egarantContractData;
    protected DocumentsCheckData documentsCheckData;
    @XmlElement(required = true)
    protected InsuranceContract insuranceContract;

    /**
     * Gets the value of the egarantContractData property.
     * 
     * @return
     *     possible object is
     *     {@link EgarantContractData }
     *     
     */
    public EgarantContractData getEgarantContractData() {
        return egarantContractData;
    }

    /**
     * Sets the value of the egarantContractData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EgarantContractData }
     *     
     */
    public void setEgarantContractData(EgarantContractData value) {
        this.egarantContractData = value;
    }

    /**
     * Gets the value of the documentsCheckData property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentsCheckData }
     *     
     */
    public DocumentsCheckData getDocumentsCheckData() {
        return documentsCheckData;
    }

    /**
     * Sets the value of the documentsCheckData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentsCheckData }
     *     
     */
    public void setDocumentsCheckData(DocumentsCheckData value) {
        this.documentsCheckData = value;
    }

    /**
     * Gets the value of the insuranceContract property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceContract }
     *     
     */
    public InsuranceContract getInsuranceContract() {
        return insuranceContract;
    }

    /**
     * Sets the value of the insuranceContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceContract }
     *     
     */
    public void setInsuranceContract(InsuranceContract value) {
        this.insuranceContract = value;
    }

}
