//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:34:06 AM MSK 
//


package app.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for Rates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rates"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tb" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="kt" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="kbm" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="ko" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="kvs" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="km" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="kpr" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="kn" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="ks" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rates", propOrder = {
    "tb",
    "kt",
    "kbm",
    "ko",
    "kvs",
    "km",
    "kpr",
    "kn",
    "ks"
})
public class Rates {

    @XmlElement(required = true)
    protected BigDecimal tb;
    @XmlElement(required = true)
    protected BigDecimal kt;
    @XmlElement(required = true)
    protected BigDecimal kbm;
    @XmlElement(required = true)
    protected BigDecimal ko;
    @XmlElement(required = true)
    protected BigDecimal kvs;
    @XmlElement(required = true)
    protected BigDecimal km;
    @XmlElement(required = true)
    protected BigDecimal kpr;
    @XmlElement(required = true)
    protected BigDecimal kn;
    protected BigDecimal ks;

    /**
     * Gets the value of the tb property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTb() {
        return tb;
    }

    /**
     * Sets the value of the tb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTb(BigDecimal value) {
        this.tb = value;
    }

    /**
     * Gets the value of the kt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKt() {
        return kt;
    }

    /**
     * Sets the value of the kt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKt(BigDecimal value) {
        this.kt = value;
    }

    /**
     * Gets the value of the kbm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKbm() {
        return kbm;
    }

    /**
     * Sets the value of the kbm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKbm(BigDecimal value) {
        this.kbm = value;
    }

    /**
     * Gets the value of the ko property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKo() {
        return ko;
    }

    /**
     * Sets the value of the ko property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKo(BigDecimal value) {
        this.ko = value;
    }

    /**
     * Gets the value of the kvs property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKvs() {
        return kvs;
    }

    /**
     * Sets the value of the kvs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKvs(BigDecimal value) {
        this.kvs = value;
    }

    /**
     * Gets the value of the km property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKm() {
        return km;
    }

    /**
     * Sets the value of the km property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKm(BigDecimal value) {
        this.km = value;
    }

    /**
     * Gets the value of the kpr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKpr() {
        return kpr;
    }

    /**
     * Sets the value of the kpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKpr(BigDecimal value) {
        this.kpr = value;
    }

    /**
     * Gets the value of the kn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKn() {
        return kn;
    }

    /**
     * Sets the value of the kn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKn(BigDecimal value) {
        this.kn = value;
    }

    /**
     * Gets the value of the ks property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKs() {
        return ks;
    }

    /**
     * Sets the value of the ks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKs(BigDecimal value) {
        this.ks = value;
    }

}
