//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:34:06 AM MSK 
//


package app.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Vehicle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Vehicle"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="maintenanceCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="maintenanceCardSeries" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="maintenanceCardType" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="mdmId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="upcomingMaintenanceDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="vehicleDocument" type="{}VehicleDocument"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Vehicle", propOrder = {
    "maintenanceCardNumber",
    "maintenanceCardSeries",
    "maintenanceCardType",
    "mdmId",
    "upcomingMaintenanceDate",
    "vehicleDocument"
})
public class Vehicle {

    @XmlElement(required = true)
    protected String maintenanceCardNumber;
    @XmlElement(required = true)
    protected String maintenanceCardSeries;
    protected Long maintenanceCardType;
    protected Long mdmId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar upcomingMaintenanceDate;
    @XmlElement(required = true)
    protected VehicleDocument vehicleDocument;

    /**
     * Gets the value of the maintenanceCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaintenanceCardNumber() {
        return maintenanceCardNumber;
    }

    /**
     * Sets the value of the maintenanceCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaintenanceCardNumber(String value) {
        this.maintenanceCardNumber = value;
    }

    /**
     * Gets the value of the maintenanceCardSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaintenanceCardSeries() {
        return maintenanceCardSeries;
    }

    /**
     * Sets the value of the maintenanceCardSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaintenanceCardSeries(String value) {
        this.maintenanceCardSeries = value;
    }

    /**
     * Gets the value of the maintenanceCardType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaintenanceCardType() {
        return maintenanceCardType;
    }

    /**
     * Sets the value of the maintenanceCardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaintenanceCardType(Long value) {
        this.maintenanceCardType = value;
    }

    /**
     * Gets the value of the mdmId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMdmId() {
        return mdmId;
    }

    /**
     * Sets the value of the mdmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMdmId(Long value) {
        this.mdmId = value;
    }

    /**
     * Gets the value of the upcomingMaintenanceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpcomingMaintenanceDate() {
        return upcomingMaintenanceDate;
    }

    /**
     * Sets the value of the upcomingMaintenanceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpcomingMaintenanceDate(XMLGregorianCalendar value) {
        this.upcomingMaintenanceDate = value;
    }

    /**
     * Gets the value of the vehicleDocument property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleDocument }
     *     
     */
    public VehicleDocument getVehicleDocument() {
        return vehicleDocument;
    }

    /**
     * Sets the value of the vehicleDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleDocument }
     *     
     */
    public void setVehicleDocument(VehicleDocument value) {
        this.vehicleDocument = value;
    }

}
