//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:34:06 AM MSK 
//


package app.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for VehicleDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleDocument"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}BaseDoc"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bodyNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="chassisNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="licensePlate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="writtenMake" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="writtenModel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productionYear" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="powerHp" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="maxAllowedWeight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="passengerCapacity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="vehicleType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vehicleCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="modification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleDocument", propOrder = {
    "vin",
    "bodyNumber",
    "chassisNumber",
    "licensePlate",
    "writtenMake",
    "writtenModel",
    "productionYear",
    "powerHp",
    "maxAllowedWeight",
    "passengerCapacity",
    "vehicleType",
    "vehicleCategory",
    "modification"
})
public class VehicleDocument
    extends BaseDoc
{

    @XmlElement(required = true)
    protected String vin;
    @XmlElement(required = true)
    protected String bodyNumber;
    @XmlElement(required = true)
    protected String chassisNumber;
    @XmlElement(required = true)
    protected String licensePlate;
    @XmlElement(required = true)
    protected String writtenMake;
    @XmlElement(required = true)
    protected String writtenModel;
    @XmlElement(required = true)
    protected BigInteger productionYear;
    @XmlElement(required = true)
    protected BigDecimal powerHp;
    protected Integer maxAllowedWeight;
    protected Integer passengerCapacity;
    protected String vehicleType;
    protected String vehicleCategory;
    protected String modification;

    /**
     * Gets the value of the vin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVin() {
        return vin;
    }

    /**
     * Sets the value of the vin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVin(String value) {
        this.vin = value;
    }

    /**
     * Gets the value of the bodyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBodyNumber() {
        return bodyNumber;
    }

    /**
     * Sets the value of the bodyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBodyNumber(String value) {
        this.bodyNumber = value;
    }

    /**
     * Gets the value of the chassisNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChassisNumber() {
        return chassisNumber;
    }

    /**
     * Sets the value of the chassisNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChassisNumber(String value) {
        this.chassisNumber = value;
    }

    /**
     * Gets the value of the licensePlate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicensePlate() {
        return licensePlate;
    }

    /**
     * Sets the value of the licensePlate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicensePlate(String value) {
        this.licensePlate = value;
    }

    /**
     * Gets the value of the writtenMake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrittenMake() {
        return writtenMake;
    }

    /**
     * Sets the value of the writtenMake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrittenMake(String value) {
        this.writtenMake = value;
    }

    /**
     * Gets the value of the writtenModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrittenModel() {
        return writtenModel;
    }

    /**
     * Sets the value of the writtenModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrittenModel(String value) {
        this.writtenModel = value;
    }

    /**
     * Gets the value of the productionYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProductionYear() {
        return productionYear;
    }

    /**
     * Sets the value of the productionYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductionYear(BigInteger value) {
        this.productionYear = value;
    }

    /**
     * Gets the value of the powerHp property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPowerHp() {
        return powerHp;
    }

    /**
     * Sets the value of the powerHp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPowerHp(BigDecimal value) {
        this.powerHp = value;
    }

    /**
     * Gets the value of the maxAllowedWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxAllowedWeight() {
        return maxAllowedWeight;
    }

    /**
     * Sets the value of the maxAllowedWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxAllowedWeight(Integer value) {
        this.maxAllowedWeight = value;
    }

    /**
     * Gets the value of the passengerCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPassengerCapacity() {
        return passengerCapacity;
    }

    /**
     * Sets the value of the passengerCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPassengerCapacity(Integer value) {
        this.passengerCapacity = value;
    }

    /**
     * Gets the value of the vehicleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleType(String value) {
        this.vehicleType = value;
    }

    /**
     * Gets the value of the vehicleCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleCategory() {
        return vehicleCategory;
    }

    /**
     * Sets the value of the vehicleCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleCategory(String value) {
        this.vehicleCategory = value;
    }

    /**
     * Gets the value of the modification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModification() {
        return modification;
    }

    /**
     * Sets the value of the modification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModification(String value) {
        this.modification = value;
    }

}
